### ISSUE TITLE
Incompatibility issue with eslint-config-prettier 8

### ISSUE THREAD

**Issue by pur3miish** [jaydenseric/eslint-config-env#3]
### Description of issue

`eslint-config-env` requires `eslint-prettier-react` as a dependency while [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) throws an error if it is.

<img width="1156" alt="Screen Shot 2021-03-28 at 2 53 23 pm" src="https://user-images.githubusercontent.com/16223777/112742840-5ada6400-8fd5-11eb-8c9e-46f345828c6c.png">

### Source of issue
[eslint-config-prettier@8.0.0](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21) have merged prettier/react into prettier. 

#### Hack around  
In the mean time deprecating `eslint-config-prettier` to 7 will continue to works as expected.

**Comment by jaydenseric** [comment]
Yes, I'm been aware of this for a while now but have been too busy getting the major new version of `graphql-react` out to work on it. In the meantime, in your app just don't update `eslint-config-prettier` past v7, or `eslint-plugin-jsdoc` past v31.

It will be a bit of work to update support for the new versions of both here, but the good news is that the end result will be a lot simpler. I also hope to improve JSDoc `@example` code block linting while I'm at it, adding Pretter formatting to markdown code blocks within.

**Comment by jaydenseric** [comment]
The fix has been published in [v19.0.0](https://github.com/jaydenseric/eslint-config-env/releases/tag/v19.0.0) 🚀
